// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muster.Persistence;

#nullable disable

namespace Muster.Persistence.Migrations
{
    [DbContext(typeof(MusterDbContext))]
    [Migration("20260603131237_NullableTrackingDefaults")]
    partial class NullableTrackingDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Currencies.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsSeasonal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpendable")
                        .HasColumnType("bit");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Code")
                        .IsUnique();

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Currencies.CurrencyBulkBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActorId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("AppliedCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Delta")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("TargetUserIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Status");

                    b.ToTable("CurrencyBulkBatches");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Currencies.CurrencyLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique()
                        .HasFilter("[SourceId] IS NOT NULL");

                    b.HasIndex("GuildId", "UserId", "CurrencyId", "SeasonId");

                    b.ToTable("CurrencyLedgerEntries");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Currencies.CurrencyWebhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset?>("LastDeliveryAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LastStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Secret")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SourceFilter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Enabled");

                    b.ToTable("CurrencyWebhooks");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Currencies.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Status");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Currencies.Wallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "CurrencyId", "SeasonId")
                        .IsUnique()
                        .HasFilter("[SeasonId] IS NOT NULL");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Events.EventAttendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("MarkedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SignedUpAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("EventAttendees");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Events.GuildEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CreatedBy")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("MessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RewardAmount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RewardCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ScheduledEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ScheduledStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StatusChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("TrackingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Status");

                    b.ToTable("GuildEvents");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Guilds.Guild", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("IconHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Guilds.GuildMusterSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.PrimitiveCollection<string>("AllowedChannelIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutoCreateChannel")
                        .HasColumnType("int");

                    b.Property<int>("AutoCreateGate")
                        .HasColumnType("int");

                    b.Property<bool>("AutoCreateOnSession")
                        .HasColumnType("bit");

                    b.Property<int>("BoardRetentionHours")
                        .HasColumnType("int");

                    b.Property<bool>("CreatorAutoCheckIn")
                        .HasColumnType("bit");

                    b.Property<Guid?>("DefaultCoinCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DefaultCoins")
                        .HasColumnType("bigint");

                    b.Property<int>("DefaultExpiryHours")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultMinCheckIns")
                        .HasColumnType("int");

                    b.Property<long>("DefaultPoints")
                        .HasColumnType("bigint");

                    b.Property<int>("DefaultResolveMode")
                        .HasColumnType("int");

                    b.Property<decimal>("MusterChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("GuildMusterSettings");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Guilds.GuildTrackingSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("ActivityRetentionDays")
                        .HasColumnType("int");

                    b.Property<bool>("BackgroundTrackingOptIn")
                        .HasColumnType("bit");

                    b.Property<int>("DefaultBackgroundGuards")
                        .HasColumnType("int");

                    b.Property<int>("DefaultEventGuards")
                        .HasColumnType("int");

                    b.Property<int>("DefaultSessionGuards")
                        .HasColumnType("int");

                    b.Property<int>("EndBonusWindowMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MaxSessionHours")
                        .HasColumnType("int");

                    b.Property<int?>("MinTrackedSeconds")
                        .HasColumnType("int");

                    b.Property<int>("MinutesPerCoin")
                        .HasColumnType("int");

                    b.Property<decimal?>("MultiplierCap")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.Property<int>("MultiplierStacking")
                        .HasColumnType("int");

                    b.Property<bool>("MultiplyPresenceBonuses")
                        .HasColumnType("bit");

                    b.Property<int>("PointsPerVoiceMinute")
                        .HasColumnType("int");

                    b.Property<string>("SessionCoinCurrencyCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("SessionEndBonus")
                        .HasColumnType("int");

                    b.Property<int>("SessionStartBonus")
                        .HasColumnType("int");

                    b.Property<int>("StartBonusWindowMinutes")
                        .HasColumnType("int");

                    b.HasKey("GuildId");

                    b.ToTable("GuildTrackingSettings");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Members.DiscordUser", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("AvatarHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CurrencyDmOptOut")
                        .HasColumnType("bit");

                    b.Property<string>("GlobalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBot")
                        .HasColumnType("bit");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Members.GuildChannel", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("BackgroundGuards")
                        .HasColumnType("int");

                    b.Property<int>("DailyCapPoints")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("EventGuards")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("MessageCooldownSeconds")
                        .HasColumnType("int");

                    b.Property<int>("MessageDailyCapPoints")
                        .HasColumnType("int");

                    b.Property<int>("MessagesPerPoint")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("OccupiedSince")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PointsPerMessage")
                        .HasColumnType("int");

                    b.Property<int>("PointsPerMinute")
                        .HasColumnType("int");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("SessionGuards")
                        .HasColumnType("int");

                    b.HasKey("GuildId", "ChannelId");

                    b.HasIndex("GuildId", "Kind");

                    b.HasIndex("GuildId", "Mode");

                    b.ToTable("GuildChannels");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Members.GuildMember", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("RoleIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tracking")
                        .HasColumnType("int");

                    b.HasKey("GuildId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Members.GuildRole", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Permissions")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("GuildId", "RoleId");

                    b.ToTable("GuildRoles");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Musters.MusterSessionLink", b =>
                {
                    b.Property<Guid>("MusterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MusterId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("MusterSessionLinks");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Musters.MusterTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("CoinCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Coins")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int?>("ExpiryHours")
                        .HasColumnType("int");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("MinCheckIns")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Points")
                        .HasColumnType("bigint");

                    b.Property<string>("Prompt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ResolveMode")
                        .HasColumnType("int");

                    b.Property<int>("RetentionHours")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Enabled");

                    b.ToTable("MusterTemplates");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Musters.ReactionMuster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CoinCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Coins")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CreatedBy")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("MinCheckIns")
                        .HasColumnType("int");

                    b.Property<long>("Points")
                        .HasColumnType("bigint");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResolveMode")
                        .HasColumnType("int");

                    b.Property<int>("RetentionHours")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Status");

                    b.ToTable("ReactionMusters");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Musters.ReactionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CheckedInAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MusterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("MusterId", "UserId")
                        .IsUnique();

                    b.ToTable("ReactionParticipants");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Operations.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActsAsUserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApiClients");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Operations.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ActorUserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Origin")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetUserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "CorrelationId");

                    b.HasIndex("GuildId", "OccurredAt");

                    b.HasIndex("GuildId", "TargetUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Operations.PostedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("EverPublic")
                        .HasColumnType("bit");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId")
                        .IsUnique();

                    b.ToTable("PostedMessages");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Quests.GuildQuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("BonusPoints")
                        .HasColumnType("bigint");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CreatedBy")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeadlineReminderSentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisputeReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DisputedBy")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("EscrowAmount")
                        .HasColumnType("bigint");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Origin")
                        .HasColumnType("int");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("RequiresFinalApproval")
                        .HasColumnType("bit");

                    b.Property<long>("RewardAmount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RewardCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("ScheduledStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StatusChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Status");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Quests.QuestParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("ReviewedBy")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("QuestId", "UserId");

                    b.ToTable("QuestParticipants");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Tracking.ActivityRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("SourceMessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("TrackingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("SourceMessageId")
                        .IsUnique()
                        .HasFilter("[SourceMessageId] IS NOT NULL");

                    b.ToTable("ActivityRecords");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Tracking.BackgroundVoicePresence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveCarrySeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ActiveOpenSegmentStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("AwardedDate")
                        .HasColumnType("date");

                    b.Property<int>("AwardedPointsToday")
                        .HasColumnType("int");

                    b.Property<int>("CarrySeconds")
                        .HasColumnType("int");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset?>("OpenSegmentStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PresentSince")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "ChannelId")
                        .IsUnique();

                    b.ToTable("BackgroundVoicePresences");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Tracking.DailyActivityRollup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("VoiceMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "ChannelId", "Date")
                        .IsUnique();

                    b.ToTable("DailyActivityRollups");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Tracking.MessageRewardState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AwardedDate")
                        .HasColumnType("date");

                    b.Property<int>("AwardedPointsToday")
                        .HasColumnType("int");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset?>("LastRewardAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MessagesSinceAward")
                        .HasColumnType("int");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "ChannelId")
                        .IsUnique();

                    b.ToTable("MessageRewardStates");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Tracking.RewardMultiplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Factor")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("MinMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MinPeopleInChannel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Enabled");

                    b.ToTable("RewardMultipliers");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Tracking.SeasonParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("VoiceMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId", "SeasonId")
                        .IsUnique();

                    b.ToTable("SeasonParticipations");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Tracking.SessionOptOut", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "UserId")
                        .IsUnique();

                    b.ToTable("SessionOptOuts");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Tracking.SessionPresenceEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "AtUtc");

                    b.ToTable("SessionPresenceEvents");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Tracking.TrackingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoinGate")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Guards")
                        .HasColumnType("int");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OpenedBy")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("ScheduledEventId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("VoiceChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("VoiceChannelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "ScheduledEventId")
                        .IsUnique()
                        .HasFilter("[Status] = 0 AND [ScheduledEventId] IS NOT NULL");

                    b.HasIndex("GuildId", "Status");

                    b.ToTable("TrackingSessions");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Tracking.VoiceAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CarrySeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FirstJoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("InChannel")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLeftAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("OpenSegmentStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("TrackingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("WeightedSeconds")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TrackingSessionId", "UserId")
                        .IsUnique();

                    b.ToTable("VoiceAttendance");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Currencies.Currency", b =>
                {
                    b.OwnsOne("Muster.Domain.Entities.Currencies.CurrencyConnector", "Connector", b1 =>
                        {
                            b1.Property<Guid>("CurrencyId");

                            b1.Property<string>("BaseUrl");

                            b1.Property<bool>("Enabled");

                            b1.Property<string>("ErrorPath");

                            b1.Property<string>("IdempotencyHeader");

                            b1.Property<DateTimeOffset?>("LastAttemptAt");

                            b1.Property<string>("LastError");

                            b1.Property<string>("LastStatus");

                            b1.Property<string>("SuccessCodes");

                            b1.Property<int>("SyncIntervalMinutes");

                            b1.Property<int>("TimeoutSeconds");

                            b1.HasKey("CurrencyId");

                            b1.ToTable("Currencies");

                            b1
                                .ToJson("Connector")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CurrencyId");

                            b1.OwnsOne("Muster.Domain.Entities.Currencies.ConnectorAuth", "Auth", b2 =>
                                {
                                    b2.Property<Guid>("CurrencyConnectorCurrencyId");

                                    b2.Property<int>("ApiKeyIn");

                                    b2.Property<string>("ApiKeyName")
                                        .IsRequired();

                                    b2.Property<int>("Scheme");

                                    b2.Property<string>("Secret");

                                    b2.Property<string>("Username");

                                    b2.HasKey("CurrencyConnectorCurrencyId");

                                    b2.ToTable("Currencies");

                                    b2.WithOwner()
                                        .HasForeignKey("CurrencyConnectorCurrencyId");
                                });

                            b1.OwnsMany("Muster.Domain.Entities.Currencies.ConnectorHeader", "Headers", b2 =>
                                {
                                    b2.Property<Guid>("CurrencyConnectorCurrencyId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired();

                                    b2.HasKey("CurrencyConnectorCurrencyId", "__synthesizedOrdinal");

                                    b2.ToTable("Currencies");

                                    b2.WithOwner()
                                        .HasForeignKey("CurrencyConnectorCurrencyId");
                                });

                            b1.OwnsOne("Muster.Domain.Entities.Currencies.ConnectorSigning", "Signing", b2 =>
                                {
                                    b2.Property<Guid>("CurrencyConnectorCurrencyId");

                                    b2.Property<int>("Algorithm");

                                    b2.Property<string>("Secret");

                                    b2.Property<string>("SignatureHeader")
                                        .IsRequired();

                                    b2.Property<string>("TimestampHeader");

                                    b2.HasKey("CurrencyConnectorCurrencyId");

                                    b2.ToTable("Currencies");

                                    b2.WithOwner()
                                        .HasForeignKey("CurrencyConnectorCurrencyId");
                                });

                            b1.OwnsOne("Muster.Domain.Entities.Currencies.ConnectorAction", "Credit", b2 =>
                                {
                                    b2.Property<Guid>("CurrencyConnectorCurrencyId");

                                    b2.Property<int>("BodyFormat");

                                    b2.Property<string>("BodyTemplate");

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("Method")
                                        .IsRequired();

                                    b2.Property<string>("Path");

                                    b2.Property<string>("Query");

                                    b2.Property<int>("ResponseFormat");

                                    b2.Property<string>("ResponsePath");

                                    b2.HasKey("CurrencyConnectorCurrencyId");

                                    b2.ToTable("Currencies");

                                    b2.WithOwner()
                                        .HasForeignKey("CurrencyConnectorCurrencyId");
                                });

                            b1.OwnsOne("Muster.Domain.Entities.Currencies.ConnectorAction", "Debit", b2 =>
                                {
                                    b2.Property<Guid>("CurrencyConnectorCurrencyId");

                                    b2.Property<int>("BodyFormat");

                                    b2.Property<string>("BodyTemplate");

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("Method")
                                        .IsRequired();

                                    b2.Property<string>("Path");

                                    b2.Property<string>("Query");

                                    b2.Property<int>("ResponseFormat");

                                    b2.Property<string>("ResponsePath");

                                    b2.HasKey("CurrencyConnectorCurrencyId");

                                    b2.ToTable("Currencies");

                                    b2.WithOwner()
                                        .HasForeignKey("CurrencyConnectorCurrencyId");
                                });

                            b1.OwnsOne("Muster.Domain.Entities.Currencies.ConnectorAction", "GetBalance", b2 =>
                                {
                                    b2.Property<Guid>("CurrencyConnectorCurrencyId");

                                    b2.Property<int>("BodyFormat");

                                    b2.Property<string>("BodyTemplate");

                                    b2.Property<bool>("Enabled");

                                    b2.Property<string>("Method")
                                        .IsRequired();

                                    b2.Property<string>("Path");

                                    b2.Property<string>("Query");

                                    b2.Property<int>("ResponseFormat");

                                    b2.Property<string>("ResponsePath");

                                    b2.HasKey("CurrencyConnectorCurrencyId");

                                    b2.ToTable("Currencies");

                                    b2.WithOwner()
                                        .HasForeignKey("CurrencyConnectorCurrencyId");
                                });

                            b1.Navigation("Auth")
                                .IsRequired();

                            b1.Navigation("Credit")
                                .IsRequired();

                            b1.Navigation("Debit")
                                .IsRequired();

                            b1.Navigation("GetBalance")
                                .IsRequired();

                            b1.Navigation("Headers");

                            b1.Navigation("Signing")
                                .IsRequired();
                        });

                    b.Navigation("Connector")
                        .IsRequired();
                });

            modelBuilder.Entity("Muster.Domain.Entities.Events.EventAttendee", b =>
                {
                    b.HasOne("Muster.Domain.Entities.Events.GuildEvent", "Event")
                        .WithMany("Attendees")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Guilds.Guild", b =>
                {
                    b.OwnsOne("Muster.Domain.Entities.Guilds.GuildSettings", "Settings", b1 =>
                        {
                            b1.Property<decimal>("GuildId");

                            b1.PrimitiveCollection<string>("AdminRoleIds")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("AuditorRoleIds")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("EconomyManagerRoleIds")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("EventOfficerRoleIds")
                                .IsRequired();

                            b1.Property<int>("LedgerRetentionDays");

                            b1.PrimitiveCollection<string>("MusterCreatorRoleIds")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("OfficerRoleIds")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("ParticipantRoleIds")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("QuestManagerRoleIds")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("TrackingManagerRoleIds")
                                .IsRequired();

                            b1.HasKey("GuildId");

                            b1.ToTable("Guilds");

                            b1
                                .ToJson("Settings")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("GuildId");

                            b1.OwnsOne("Muster.Domain.Entities.Guilds.QuestSettings", "Quests", b2 =>
                                {
                                    b2.Property<decimal>("GuildSettingsGuildId");

                                    b2.Property<bool>("AllowSelfParticipation");

                                    b2.Property<int>("BoardRetentionHours");

                                    b2.Property<int>("ClaimTimeoutHours");

                                    b2.Property<int>("DeadlineReminderHours");

                                    b2.Property<int>("DisputeTimeoutHours");

                                    b2.Property<int>("FinalApprovalMode");

                                    b2.Property<int>("FinalApprovalTimeoutAction");

                                    b2.Property<int>("FinalApprovalTimeoutHours");

                                    b2.Property<int>("IntakeTimeoutAction");

                                    b2.Property<int>("IntakeTimeoutHours");

                                    b2.Property<int>("MaxActiveClaimsPerUser");

                                    b2.Property<int>("MaxOpenQuestsPerPoster");

                                    b2.Property<int>("MaxRevisions");

                                    b2.Property<bool>("PersonalQuestIntakeApproval");

                                    b2.Property<decimal>("QuestChannelId");

                                    b2.Property<decimal>("QuestModChannelId");

                                    b2.Property<bool>("QuestsRequireApproval");

                                    b2.Property<int>("SubmissionTimeoutAction");

                                    b2.Property<int>("SubmissionTimeoutHours");

                                    b2.Property<long>("TierAPoints");

                                    b2.Property<long>("TierBPoints");

                                    b2.Property<long>("TierCPoints");

                                    b2.Property<long>("TierDPoints");

                                    b2.Property<long>("TierEPoints");

                                    b2.Property<long>("TierSPoints");

                                    b2.HasKey("GuildSettingsGuildId");

                                    b2.ToTable("Guilds");

                                    b2.WithOwner()
                                        .HasForeignKey("GuildSettingsGuildId");
                                });

                            b1.Navigation("Quests")
                                .IsRequired();
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("Muster.Domain.Entities.Guilds.GuildMusterSettings", b =>
                {
                    b.HasOne("Muster.Domain.Entities.Guilds.Guild", null)
                        .WithOne()
                        .HasForeignKey("Muster.Domain.Entities.Guilds.GuildMusterSettings", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Muster.Domain.Entities.Guilds.GuildTrackingSettings", b =>
                {
                    b.HasOne("Muster.Domain.Entities.Guilds.Guild", null)
                        .WithOne()
                        .HasForeignKey("Muster.Domain.Entities.Guilds.GuildTrackingSettings", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Muster.Domain.Entities.Members.GuildMember", b =>
                {
                    b.HasOne("Muster.Domain.Entities.Guilds.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Muster.Domain.Entities.Members.DiscordUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Musters.MusterSessionLink", b =>
                {
                    b.HasOne("Muster.Domain.Entities.Musters.ReactionMuster", "Muster")
                        .WithMany("SessionLinks")
                        .HasForeignKey("MusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muster");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Musters.ReactionParticipant", b =>
                {
                    b.HasOne("Muster.Domain.Entities.Musters.ReactionMuster", "Muster")
                        .WithMany("Participants")
                        .HasForeignKey("MusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muster");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Quests.QuestParticipant", b =>
                {
                    b.HasOne("Muster.Domain.Entities.Quests.GuildQuest", "Quest")
                        .WithMany("Participants")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Tracking.VoiceAttendance", b =>
                {
                    b.HasOne("Muster.Domain.Entities.Tracking.TrackingSession", "TrackingSession")
                        .WithMany("Attendance")
                        .HasForeignKey("TrackingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackingSession");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Events.GuildEvent", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Musters.ReactionMuster", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("SessionLinks");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Quests.GuildQuest", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Muster.Domain.Entities.Tracking.TrackingSession", b =>
                {
                    b.Navigation("Attendance");
                });
#pragma warning restore 612, 618
        }
    }
}
