<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Muster.Integration.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Blobs" />
    <PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Keys" />
    <PackageReference Include="Aspire.Azure.Security.KeyVault" />
    <PackageReference Include="Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration" />
    <PackageReference Include="Aspire.Azure.Storage.Blobs" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.SqlServer" />
    <PackageReference Include="WolverineFx.AzureServiceBus" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Muster.Domain\Muster.Domain.csproj" />
    <ProjectReference Include="..\Muster.Contracts\Muster.Contracts.csproj" />
    <ProjectReference Include="..\Muster.Persistence\Muster.Persistence.csproj" />
  </ItemGroup>

</Project>
