<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Muster.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Muster.Domain\Muster.Domain.csproj" />
    <ProjectReference Include="..\Muster.Contracts\Muster.Contracts.csproj" />
    <ProjectReference Include="..\Muster.Persistence\Muster.Persistence.csproj" />
  </ItemGroup>

</Project>
